# Generated by Django 5.1.15 on 2026-06-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_overdraft_limit_and_more'),
        ('cards', '0004_card_is_archived'),
        ('limits', '0003_rename_accountlimit_accountlimits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountlimits',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountlimits',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='accountlimits',
            name='channel',
            field=models.CharField(choices=[('CARD', 'Card'), ('BLIK', 'KLIK code payment'), ('BLIK_PHONE', 'KLIK phone transfer')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='accountlimits',
            constraint=models.UniqueConstraint(condition=models.Q(('card__isnull', True)), fields=('account', 'channel'), name='unique_account_channel_limit'),
        ),
        migrations.AddConstraint(
            model_name='accountlimits',
            constraint=models.UniqueConstraint(condition=models.Q(('card__isnull', False)), fields=('card', 'channel'), name='unique_card_channel_limit'),
        ),
    ]
