"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b4pq76#&-197r@w&ck_4^#jc#6ip=b=_^-6o)=sok%zq*hk^h%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    
    
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    
    'users',
    'customers',
    'accounts',
    'transactions',
    'limits',
    'cards',
    'transfers',
    'notifications',
    'klik',
    'ukps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# ZMIENIONE: Połączenie z PostgreSQL w Dockerze
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'uk_bank_db'),
        'USER': os.environ.get('DB_USER', 'bank_admin'),
        'PASSWORD': os.environ.get('DB_PASS', 'secure_pass'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London' 

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'



AUTH_USER_MODEL = 'users.User'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Lyo Bank API',
    'DESCRIPTION': 'System bankowy - dokumentacja endpointów',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

KLIK_BASE_URL = os.environ.get("KLIK_BASE_URL", "http://host.docker.internal:8000/api/v1")
KLIK_BANK_API_KEY = os.environ.get("KLIK_BANK_API_KEY", "CHANGE_ME")
KLIK_ZONE = os.environ.get("KLIK_ZONE", "UK")

CARD_GATEWAY_BASE_URL = os.environ.get(
    "CARD_GATEWAY_BASE_URL",
    "http://host.docker.internal:8072"
)
CARD_GATEWAY_API_KEY = os.environ.get(
    "CARD_GATEWAY_API_KEY",
    "CHANGE_ME"
)
CARD_GATEWAY_HMAC_SECRET = os.environ.get(
    "CARD_GATEWAY_HMAC_SECRET",
    "CHANGE_ME"
)

# ---------------------------------------------------------------------------
# UK Payment Systems (UKPS) — interbank schemes CHAPS / FPS / BACS
# Reached over the host network (same pattern as KLIK / card gateway), so no
# changes are required in the external uk-payment-systems project.
# ---------------------------------------------------------------------------
UKPS_CHAPS_URL = os.environ.get("UKPS_CHAPS_URL", "http://host.docker.internal:8420")
UKPS_FPS_URL = os.environ.get("UKPS_FPS_URL", "http://host.docker.internal:8421")
UKPS_BACS_URL = os.environ.get("UKPS_BACS_URL", "http://host.docker.internal:8422")

# This bank's own identity inside UKPS. With UKPS_AUTO_REGISTER on, the bank
# registers itself in each scheme on first use (POST /v1/participants/register)
# and persists the returned API key, so the per-scheme keys below are blank.
# To instead run under a pre-seeded BIC, set its key(s) and turn auto-register
# off (e.g. UKPS_BANK_BIC=SNDRUK22 + UKPS_*_API_KEY=ak_sndruk22_dev).
UKPS_BANK_BIC = os.environ.get("UKPS_BANK_BIC", "LYOBGB2L")
UKPS_BANK_NAME = os.environ.get("UKPS_BANK_NAME", "Lyo Bank")
UKPS_BANK_SORT_CODE = os.environ.get("UKPS_BANK_SORT_CODE", "10-20-30")
UKPS_BANK_SU_CODE = os.environ.get("UKPS_BANK_SU_CODE", "SU-LYOB")
UKPS_INITIAL_LIQUIDITY = os.environ.get("UKPS_INITIAL_LIQUIDITY", "1000000")

UKPS_CHAPS_API_KEY = os.environ.get("UKPS_CHAPS_API_KEY", "")
UKPS_FPS_API_KEY = os.environ.get("UKPS_FPS_API_KEY", "")
UKPS_BACS_API_KEY = os.environ.get("UKPS_BACS_API_KEY", "")

UKPS_AUTO_REGISTER = os.environ.get("UKPS_AUTO_REGISTER", "True") == "True"

# FPS is capped at < £250,000 per payment; larger values must use CHAPS.
UKPS_FPS_MAX_AMOUNT = os.environ.get("UKPS_FPS_MAX_AMOUNT", "250000")

# Inbound: FPS events carry no destination account (the scheme has no per-account
# addressing here), so received FPS funds land in this fallback account number.
# Leave blank to record such payments as UNMATCHED instead of crediting.
UKPS_INBOUND_FALLBACK_ACCOUNT = os.environ.get("UKPS_INBOUND_FALLBACK_ACCOUNT", "")

# UKPS recipient bank directory.
# In the external UKPS simulator, domestic banks are identified by BIC,
# but the customer should not type BIC manually for FPS/BACS/CHAPS.
# The bank resolves it from the recipient IBAN sort code.
UKPS_SORT_CODE_TO_BIC = {
    "20-00-00": os.environ.get("UKPS_BIC_SORT_200000", "BARCGB2L"),
    "40-00-00": os.environ.get("UKPS_BIC_SORT_400000", "HSBCGB44"),
    "30-00-00": os.environ.get("UKPS_BIC_SORT_300000", "LLOYGB21"),
    "60-00-00": os.environ.get("UKPS_BIC_SORT_600000", "SNDRUK22"),
}


# ---------------------------------------------------------------------------
# SWIFT middleware — outgoing international transfers
# The bank acts as the already existing SWIFT mock bank UKBKGB01XXX.
# ---------------------------------------------------------------------------

SWIFT_BASE_URL = os.environ.get("SWIFT_BASE_URL", "http://host.docker.internal:3000")
SWIFT_CLIENT_ID = os.environ.get("SWIFT_CLIENT_ID", "bank-ukbkgb01")
SWIFT_CLIENT_SECRET = os.environ.get("SWIFT_CLIENT_SECRET", "secret-ukbkgb01")
SWIFT_BANK_BIC = os.environ.get("SWIFT_BANK_BIC", "UKBKGB01XXX")
SWIFT_BANK_NAME = os.environ.get("SWIFT_BANK_NAME", "Lyo Bank")
SWIFT_AUTO_SEND = os.environ.get("SWIFT_AUTO_SEND", "True") == "True"
SWIFT_TIMEOUT_SECONDS = int(os.environ.get("SWIFT_TIMEOUT_SECONDS", "15"))

# Fixed student-project FX rates.
# A value means: 1 unit of source currency buys this many units of target currency.
# Example: 1 GBP = 1.25 USD.
SWIFT_EXCHANGE_RATES = {
    ("GBP", "USD"): os.environ.get("SWIFT_RATE_GBP_USD", "1.25"),
    ("GBP", "EUR"): os.environ.get("SWIFT_RATE_GBP_EUR", "1.15"),
    ("GBP", "PLN"): os.environ.get("SWIFT_RATE_GBP_PLN", "5.00"),
    ("GBP", "GBP"): "1.00",
}

# Local sender-side fees charged by this bank, in sender account currency.
SWIFT_FEE_OUR_GBP = os.environ.get("SWIFT_FEE_OUR_GBP", "15.00")
SWIFT_FEE_SHA_GBP = os.environ.get("SWIFT_FEE_SHA_GBP", "5.00")
SWIFT_FEE_BEN_GBP = os.environ.get("SWIFT_FEE_BEN_GBP", "0.00")
