"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b4pq76#&-197r@w&ck_4^#jc#6ip=b=_^-6o)=sok%zq*hk^h%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    
    
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    
    'users',
    'customers',
    'accounts',
    'transactions',
    'limits',
    'cards',
    'transfers',
    'notifications',
    'klik',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# ZMIENIONE: Połączenie z PostgreSQL w Dockerze
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'uk_bank_db'),
        'USER': os.environ.get('DB_USER', 'bank_admin'),
        'PASSWORD': os.environ.get('DB_PASS', 'secure_pass'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London' 

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'



AUTH_USER_MODEL = 'users.User'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Lyo Bank API',
    'DESCRIPTION': 'System bankowy - dokumentacja endpointów',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

KLIK_BASE_URL = os.environ.get("KLIK_BASE_URL", "http://host.docker.internal:8000/api/v1")
KLIK_BANK_API_KEY = os.environ.get("KLIK_BANK_API_KEY", "CHANGE_ME")
KLIK_ZONE = os.environ.get("KLIK_ZONE", "UK")

CARD_GATEWAY_BASE_URL = os.environ.get(
    "CARD_GATEWAY_BASE_URL",
    "http://host.docker.internal:8072"
)
CARD_GATEWAY_API_KEY = os.environ.get(
    "CARD_GATEWAY_API_KEY",
    "CHANGE_ME"
)
CARD_GATEWAY_HMAC_SECRET = os.environ.get(
    "CARD_GATEWAY_HMAC_SECRET",
    "CHANGE_ME"
)
