# Generated by Django 5.1.15 on 2026-06-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0003_juniorapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKPSRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('CHAPS', 'CHAPS'), ('FPS', 'Faster Payments'), ('BACS', 'BACS')], max_length=8, unique=True)),
                ('bic', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('sort_code', models.CharField(max_length=9)),
                ('api_key', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UKPSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('CHAPS', 'CHAPS'), ('FPS', 'Faster Payments'), ('BACS', 'BACS')], max_length=8)),
                ('msg_id', models.CharField(db_index=True, max_length=35)),
                ('sender_bic', models.CharField(max_length=11)),
                ('receiver_bic', models.CharField(max_length=11)),
                ('receiver_sort_code', models.CharField(blank=True, max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('SETTLED', 'Settled'), ('QUEUED', 'Queued'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], max_length=12)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ukps_payments', to='transfers.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
