# Generated by Django 5.1.15 on 2026-06-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_overdraft_limit_and_more'),
        ('ukps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKPSInboundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('CHAPS', 'CHAPS'), ('FPS', 'Faster Payments'), ('BACS', 'BACS')], max_length=8)),
                ('msg_id', models.CharField(db_index=True, max_length=64)),
                ('sender_bic', models.CharField(blank=True, max_length=11)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account_number', models.CharField(blank=True, max_length=34)),
                ('status', models.CharField(choices=[('CREDITED', 'Credited'), ('UNMATCHED', 'Unmatched'), ('CYCLE_SETTLED', 'Cycle settled')], max_length=16)),
                ('raw_event', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ukps_inbound', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scheme', 'msg_id')},
            },
        ),
    ]
