# Generated by Django 5.1.15 on 2026-06-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukps', '0002_ukpsinboundpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukpsregistration',
            name='bacs_settled_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
