# Generated by Django 5.1.15 on 2026-06-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='klik_phone_alias',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
