# Generated by Django 5.1.15 on 2026-06-08 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_card_type_card_cvv_card_full_number_card_pin_and_more'),
        ('transactions', '0002_transaction_balance_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_transaction_id', models.CharField(max_length=100, unique=True)),
                ('authorization_code', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_captures', to='cards.card')),
                ('local_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_payment_capture', to='transactions.transaction')),
            ],
        ),
    ]
